org.gradle.jvmargs=-Xmx5G
org.gradle.parallel=true
org.gradle.caching=true

org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=true

mod.id=mobends
mod.name=Mo' Bends
mod.version=5.4.1
mod.group=com.thatsoulyguy
mod.license=MIT
mod.authors=GoblinBob, ThatSoulyGuy, Sxilverr
mod.description=If you think that Minecraft characters could be more realistic, instead of steady and rigid animations, this mod is just for you! Mo' Bends adds a variety of different player animations including epic sword animations!

mod.mc_dep_forgelike=[VERSIONED]
mod.pack_format=[VERSIONED]
mod.loader_range=[VERSIONED]
mod.forge_range=[VERSIONED]
mod.neoforge_range=[VERSIONED]

deps.architectury=[VERSIONED]
deps.forge_loader=[VERSIONED]
deps.neoforge_loader=[VERSIONED]
deps.curios=[VERSIONED]
deps.armourers_workshop=[VERSIONED]
