# This is an example neoforge.mods.toml file. It contains the data relating to the loading mods.
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/GoblinBob/MoBends/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://mobends.com/mod-update.json"
displayURL="https://mobends.com"
logoFile="assets/mobends/textures/logo512.png"
credits="Tommsy64 - coding support"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"

[[mixins]]
config="mobends.mixins.json"
